### ISSUE TITLE
Update to Python 3 and Django 2.2/3.0

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/monitoring#6]
Decide on using Django 2.2 LTS (long-term support release) or 3.0 and making sure we update (https://www.djangoproject.com/download/).

LTS is good for stability, but jump to next LTS version may require more work. In some respects we shouldn't need absolute stability and should be able to update frequently as the Django database can be regenerated from the Accounting database.

**Comment by jrha** [comment]
I note that the codebase is now using Django 2.2, so sticking with that would seem pragmatic.

**Comment by tofu-rocketry** [comment]
We don't have long left on 2.2 support actually, so I'd suggest the next LTS version (3.2) would be the way to go, though that does require Python 3.

**Comment by tofu-rocketry** [comment]
Now updated.
